linters:
  disable:
    - errcheck
  enable:
    - govet
    - staticcheck
    - ineffassign
    - unused

linters-settings:
  staticcheck:
    checks:
      - "all"
      - "-SA9003"

issues:
  exclude-dirs:
    - frontend
