// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cleaner} from '../models';
import {gaming} from '../models';
import {startup} from '../models';
import {toolkit} from '../models';
import {memory} from '../models';
import {monitor} from '../models';
import {network} from '../models';
import {privacy} from '../models';
import {system} from '../models';

export function ApplyAllPrivacy():Promise<void>;

export function ApplyGameProfile(arg1:string):Promise<void>;

export function CleanSystem(arg1:Array<string>):Promise<cleaner.CleanResult>;

export function DetectGPU():Promise<gaming.GPUInfo>;

export function DisableNagle():Promise<void>;

export function DisableStartupItem(arg1:startup.StartupItem):Promise<void>;

export function EnableNagle():Promise<void>;

export function EnableStartupItem(arg1:startup.StartupItem):Promise<void>;

export function FlushMemory():Promise<void>;

export function FlushNetwork():Promise<string>;

export function GetAvailableTweaks():Promise<Array<gaming.TweakInfo>>;

export function GetBloatwareApps():Promise<Array<toolkit.BloatwareApp>>;

export function GetBoostStatus():Promise<gaming.BoostStatus>;

export function GetGameProfiles():Promise<Array<gaming.GameProfile>>;

export function GetIsAdmin():Promise<boolean>;

export function GetMemoryStatus():Promise<memory.MemoryStatus>;

export function GetMonitorSnapshot():Promise<monitor.MonitorSnapshot>;

export function GetNetworkStatus():Promise<network.NetworkStatus>;

export function GetPrivacyTweaks():Promise<Array<privacy.PrivacyTweak>>;

export function GetStartupItems():Promise<Array<startup.StartupItem>>;

export function GetSystemInfo():Promise<system.SystemInfo>;

export function GetVersion():Promise<string>;

export function HasBackup():Promise<boolean>;

export function PingTest(arg1:string):Promise<number>;

export function RebuildFontCache():Promise<toolkit.ToolResult>;

export function RebuildIconCache():Promise<toolkit.ToolResult>;

export function RemoveBloatware(arg1:Array<string>):Promise<toolkit.ToolResult>;

export function RepairWindowsUpdate():Promise<toolkit.ToolResult>;

export function ResetDNS():Promise<void>;

export function ResetWindowsSearch():Promise<toolkit.ToolResult>;

export function RestoreAllBackup():Promise<void>;

export function RestoreAllPrivacy():Promise<void>;

export function RestoreGameSettings():Promise<void>;

export function RunBenchmark():Promise<monitor.BenchmarkResult>;

export function RunDISM():Promise<toolkit.ToolResult>;

export function RunSFC():Promise<toolkit.ToolResult>;

export function ScanSystem():Promise<cleaner.ScanResult>;

export function SetDNS(arg1:network.DNSPreset):Promise<void>;

export function TogglePrivacyTweak(arg1:string):Promise<void>;
