// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyAllPrivacy() {
  return window['go']['main']['App']['ApplyAllPrivacy']();
}

export function ApplyGameProfile(arg1) {
  return window['go']['main']['App']['ApplyGameProfile'](arg1);
}

export function CleanSystem(arg1) {
  return window['go']['main']['App']['CleanSystem'](arg1);
}

export function DetectGPU() {
  return window['go']['main']['App']['DetectGPU']();
}

export function DisableNagle() {
  return window['go']['main']['App']['DisableNagle']();
}

export function DisableStartupItem(arg1) {
  return window['go']['main']['App']['DisableStartupItem'](arg1);
}

export function EnableNagle() {
  return window['go']['main']['App']['EnableNagle']();
}

export function EnableStartupItem(arg1) {
  return window['go']['main']['App']['EnableStartupItem'](arg1);
}

export function FlushMemory() {
  return window['go']['main']['App']['FlushMemory']();
}

export function FlushNetwork() {
  return window['go']['main']['App']['FlushNetwork']();
}

export function GetAvailableTweaks() {
  return window['go']['main']['App']['GetAvailableTweaks']();
}

export function GetBloatwareApps() {
  return window['go']['main']['App']['GetBloatwareApps']();
}

export function GetBoostStatus() {
  return window['go']['main']['App']['GetBoostStatus']();
}

export function GetGameProfiles() {
  return window['go']['main']['App']['GetGameProfiles']();
}

export function GetIsAdmin() {
  return window['go']['main']['App']['GetIsAdmin']();
}

export function GetMemoryStatus() {
  return window['go']['main']['App']['GetMemoryStatus']();
}

export function GetMonitorSnapshot() {
  return window['go']['main']['App']['GetMonitorSnapshot']();
}

export function GetNetworkStatus() {
  return window['go']['main']['App']['GetNetworkStatus']();
}

export function GetPrivacyTweaks() {
  return window['go']['main']['App']['GetPrivacyTweaks']();
}

export function GetStartupItems() {
  return window['go']['main']['App']['GetStartupItems']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HasBackup() {
  return window['go']['main']['App']['HasBackup']();
}

export function PingTest(arg1) {
  return window['go']['main']['App']['PingTest'](arg1);
}

export function RebuildFontCache() {
  return window['go']['main']['App']['RebuildFontCache']();
}

export function RebuildIconCache() {
  return window['go']['main']['App']['RebuildIconCache']();
}

export function RemoveBloatware(arg1) {
  return window['go']['main']['App']['RemoveBloatware'](arg1);
}

export function RepairWindowsUpdate() {
  return window['go']['main']['App']['RepairWindowsUpdate']();
}

export function ResetDNS() {
  return window['go']['main']['App']['ResetDNS']();
}

export function ResetWindowsSearch() {
  return window['go']['main']['App']['ResetWindowsSearch']();
}

export function RestoreAllBackup() {
  return window['go']['main']['App']['RestoreAllBackup']();
}

export function RestoreAllPrivacy() {
  return window['go']['main']['App']['RestoreAllPrivacy']();
}

export function RestoreGameSettings() {
  return window['go']['main']['App']['RestoreGameSettings']();
}

export function RunBenchmark() {
  return window['go']['main']['App']['RunBenchmark']();
}

export function RunDISM() {
  return window['go']['main']['App']['RunDISM']();
}

export function RunSFC() {
  return window['go']['main']['App']['RunSFC']();
}

export function ScanSystem() {
  return window['go']['main']['App']['ScanSystem']();
}

export function SetDNS(arg1) {
  return window['go']['main']['App']['SetDNS'](arg1);
}

export function TogglePrivacyTweak(arg1) {
  return window['go']['main']['App']['TogglePrivacyTweak'](arg1);
}
